### ISSUE TITLE
Support schema annotations for magnolify-parquet

### ISSUE THREAD

**Issue by clairemcginty** [spotify/magnolify#591]
Annotations would be for both field-level and record-level.

Since Parquet schema [Type](https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/schema/Type.java)s don't natively support raw string annotations we'd have to decide on a standardized way to represent them in the [file metadata header](https://github.com/apache/parquet-mr/blob/master/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/metadata/FileMetaData.java#L39), too, maybe as key-value pairs like:

```yaml
annotations:
   nested.field.path: "some annotation text..."
   top-level-field: "other annotation text..."
```
